version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./api # api backend folder
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    depends_on:
      - db # Ensure the db service starts before the backend
    command: npm start

  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data: # Define a named volume for MongoDB
