version: '3'
services:
  backend:
    build:
      context: ./api #api backend folder
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    db:
      image: mongo:latest
      ports:
        - "27018:27017"
    command: npm start
